const Img=[
    {
        id:1,
        image:"languages/1.png",
        cat:"pl",
    },
    {
        id:2,
        image:"languages/2.png",
         cat:"pl",
    },
    {
        id:3,
        image:"languages/3.png",
         cat:"pl",
    },
    {
        id:4,
        image:"languages/4.png",
         cat:"pl",
    },
    {
        id:5,
        image:"languages/5.png",
         cat:"pl",
    },
    {
        id:6,
        image:"languages/6.png",
         cat:"fn",
    },
    {
        id:7,
        image:"languages/7.png",
         cat:"fn",
    },
    {
        id:8,
        image:"languages/8.png",
         cat:"fn",
    },
    {
        id:9,
        image:"languages/9.png",
         cat:"fn",
    },
    {
        id:11,
        image:"languages/11.png",
         cat:"bn",
    },
    {
        id:15,
        image:"languages/15.png",
         cat:"bn",
    },
    {
        id:12,
        image:"languages/12.png",
         cat:"db",
    },
    {
        id:13,
        image:"languages/13.png",
         cat:"db",
    },
]
export default Img